### ISSUE TITLE
Why DistributedCacheExtensions not has tryegetvakue,getorcreate extend

### ISSUE THREAD

**Issue by YINZHU2016** [aspnet/Caching#371] opened 2018-03-04 07:57 UTC
i find GetOrCreateAsync,TryGetValue good extend in memerycache,but in DistributedCacheExtensions  there is not have this,. why we have not add this method。
What is the reason for not adding these methods, it is because of performance or other problems
thanks

**Comment by muratg** [comment] 2018-06-29 22:47
Duplicate of #390

**Closed by muratg** 2018-06-29 22:47 UTC

**Comment by mungojam** [comment] 2018-06-29 22:59
Doesn't sound like a dupe to me. 

This one is asking for existing methods to be replicated across different cache types. My #390 is asking for a brand new method.

**Comment by muratg** [comment] 2018-06-29 23:17
Correct, my bad. 

https://github.com/aspnet/Caching/issues/220.

@YINZHU2016, please see https://github.com/aspnet/Caching/issues/220#issuecomment-241229013 for David's comment for more explanation on this.
