### ISSUE TITLE
Add Clear Method

### ISSUE THREAD

**Issue by rjperes** [aspnet/Caching#419] opened 2018-08-23 15:50 UTC
I'm sure this has been asked a million times, but why don't we have a Clear method on MemoryCache? I understand adding it to IMemoryCache would be problematic, as it would be a breaking change.
Thanks!

**Comment by JunTaoLuo** [comment] 2018-08-27 23:02
Can you elaborate on the purpose for which you want to clear the MemoryCache?

Originally, IMemoryCache was designed to be a shared cache between all aspnet components. As such, having a Clear method would be counterproductive since one component can remove the cache entries that was added by another component. However, we now recommend instantiating a separate MemoryCache instance for each component to better control memory usage and isolate the data stored. While we don't have a Clear method, we do have `Compact`: https://github.com/aspnet/Caching/blob/970e255413466eb05c83339bb10f57465db4f3eb/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L358-L369. This may be sufficient, depending on your use case.

I'll close the issue for now since I don't see any immediate action items. If there is any specific functionality you would like to propose please feel free to file another issue and include a sample use case. Thanks!

**Closed by JunTaoLuo** 2018-08-27 23:02 UTC
