### ISSUE TITLE
Expiration only happens during a request

### ISSUE THREAD

**Issue by strohhut** [aspnet/Caching#259] opened 2016-12-29 13:47 UTC
I set my `ExpirationScanFrequency` to 5 seconds and I'm inserting entries with 10 seconds `AbsoluteExpirationRelativeToNow`.

Problem is that those never evict if there aren't requests (or maybe they evict but `PostEvictionCallbacks` callback are only executed when there is a web request?).

Is this how it is intended? Docs don't mention that in order for `PostEvictionCallbacks` a request is necessary (but they also don't mention that callbacks are only executed after a scan.)

So I guess a scan needs a request and an expiration needs a scan?

**Comment by Tratcher** [comment] 2016-12-29 17:48
Duplicate of https://github.com/aspnet/Caching/issues/248

**Comment by Tratcher** [comment] 2016-12-29 17:52
Note ExpirationScanFrequency is a frequency limiter to prevent extra scans, not to trigger them.
https://github.com/aspnet/Caching/blob/77e4a58e2cce972c9c2f0ae64840a5d663e30d99/src/Microsoft.Extensions.Caching.Memory/MemoryCache.cs#L259

**Comment by strohhut** [comment] 2016-12-29 18:56
Thanks, I think it might be good to make this behaviour a bit more explicit by mentioning it in the docs or the XML-comments.

**Closed** 2016-12-29 18:56 UTC
Labels: duplicate
