### ISSUE TITLE
We should be able to retrieve the keys from cache

### ISSUE THREAD

**Issue by Haplois** [aspnet/Caching#171] opened 2016-03-30 01:18 UTC
I believe we should be able to retrieve keys of all current data from cache, or at least some way to purge it. Am I missing or there is no such method exists on MemoryCaching?

**Comment by Eilon** [comment] 2016-03-30 15:34
Duplicate of https://github.com/aspnet/Caching/issues/155.

**Closed by Eilon** 2016-03-30 15:34 UTC
