### ISSUE TITLE
API of ICacheManager is very limited

### ISSUE THREAD

**Issue by Eusebiogm87** [aspnet/Caching#219] opened 2016-08-19 18:02 UTC
Hello guys, i wonder why the API of the ICacheManager is so limited, we as developers need some control over the cached data, in the previous version using System.Runtime.Caching.ObjectCache we have full control, but now is very limited, think about this use cases:

In a shopping cart app, we cache categories, products, stock and some other data, when a discount is changed, it affects products but does NOT affect the entire cache, now we can't remove only the product related cache entries.

Some suggested solutions is to build a wrapper that keeps records of all added keys , i think that solution is weird and dificult when working with third party code, one possible solution could be add support for regions, for example

``` c#
ICacheManager cache = ....;

cache.Set("Dynamic unknown KEY", value, new MemoryCacheEntryOptions
                {
                    Region = "ProductCacheRegion"
                });
```

Then add a method RemoveByRegion(string region); That way we have control of cache, and the implementation of that method need to be synchronized. Some optimization may arise because you can store the cached items in diferent regions so every time a developer need to add or remove or clean a region it only affect that region, and does not affect other regions. If we don't specify a region the cached item belongs to a "global" region.

Another solution is to exposes the keys, in that way we can add our own logic, no mather when we iterate over the keys some cache entries gets expires, add docs to signal a WARNING to developers, but don't close the door, now we have no way around.

Another use case is when i want to clear the entire cache, now we can't do it, Dispose should not be the way to clear the cache, once the object is disposed we can't use it anymore, add a method Clear() that cleans the entire cache, or if regions is supported the clear method expects the region to clear "Clear(string region = null)" if the developer does not specify a region, the entire cache is cleared, but the object is NOT disposed, so we can add cache items later. In an ASP.NET app with DI is very difficult to call dispose and next time the ICacheManager is requested get a fresh instance.

**Comment by sebastienros** [comment] 2016-08-19 18:09
This is not the goal of the `ICacheManager` to provide such services, it's by design and and there is a very simple solution to it, use stringified tokens.

You can find an example in Orchard: 
https://github.com/OrchardCMS/Orchard2/blob/c46af7d9fe1893f30c28f02c186f9cd8ed9218d2/src/Orchard.Environment.Cache.Abstractions/ISignal.cs 
https://github.com/OrchardCMS/Orchard2/blob/c46af7d9fe1893f30c28f02c186f9cd8ed9218d2/src/Orchard.Environment.Cache/Signal.cs

Register is with oyur services then when you add an entry, also add a token from this. Here is how it's used:
https://github.com/OrchardCMS/Orchard2/blob/55ec536108ecdeff6ab3d1365ee07964b214e2b0/src/Orchard.Web/Modules/Orchard.Roles/Services/RoleManager.cs

This is the best solution IMO, as you can even change the implementation to broadcast the token invalidation to multiple nodes if necessary. We do it in Orchard too.

**Comment by Eusebiogm87** [comment] 2016-08-22 13:23
@sebastienros thanks for your response and suggested links.... Talking about the memory cache, that way to clear the cache is by far a lot complicated for simple scenarios, for advanced scenarios is OK, but for simple and common scenarios is a lot complicated, more complicated than my suggestion or other suggestions. About clearing the cache, even the Orchard implementation has a design flaw, how do you clear the entire cache? in your implementation i don't see that you add a clear all token, and neither see that you have a way to get all stringified tokens. Also, that way to manage the cache uses a lot more memory than other suggestions and i will assume that when you signal a Cancel on the CancellationTokenSource clearing the cache is thread safe, because on some apps you can have hundreds of cache items under the same Token.

 If you think that a clear entire cache is not useful think about this scenario:

A site owner select Orchard to build a web site, install a third party module that use cache BUT has a bug, that module has a document that depends implicitly on Roles and that module does NOT clear the cache when a Role is added/modified, how the site owner can have a work around to this issue? Now is not possible, with a clear all can mitigate the issue until a module developer publish a new version, but now is not possible.

Another issue, the actual implementation of ICacheManager will promote an API explossion, because the ICacheManager does not have an API to clear the cache, all developers will add their own API, let's say their own implementation of ISignal. For Orchard team is easy, because Orchard modules will need to follow Orchard development guidelines, but for third party libraries, guidelines does not exists, so new API to clear the cache. Then when i need to buil an application and want to use a library that use cache, i need to manage Library1API to clear cache, if another library do the same Library2API to clear the cache and a lot more dissapointing, if i need to use that libraries inside a Orchard module, i need to manage 3 API's to clear the same cache.....

Come on guys, you are a lot smarter than that, you can make the cache API a lot better and simpler, some arguments exposed are "It is risky", Reflection.Emit and AppDomain API are a lot more risky and the API is there for us, to do whatever we want !!!! following that desing rules that all things that are risky are not added, then drop support of Reflection...... I don't think that it is a solution, but actual ICacheManager implementation is closed and difficult to use.

**Comment by muratg** [comment] 2017-05-12 22:00
We are closing this issue because no further action is planned for this issue. If you still have any issues or questions, please log a new issue with any additional details that you have.

**Closed by muratg** 2017-05-12 22:00 UTC
